In [1]:
import numpy as np

# Создаем два массива размерности (10, 4) со случайными целыми числами от -5 до 5
ar1 = np.random.randint(-5, 6, size=(10, 4))
ar2 = np.random.randint(-5, 6, size=(10, 4))

# Удваиваем значения в ar1, где они больше соответствующих значений в ar2, остальные делаем 0
result = np.where(ar1 > ar2, ar1 * 2, 0)

print("Массив ar1:")
print(ar1)
print("\nМассив ar2:")
print(ar2)
print("\nРезультат:")
print(result)

Массив ar1:
[[ 2 -3  0  0]
 [-3  5  3 -3]
 [-4  5 -3  3]
 [-2 -2 -5 -5]
 [ 1 -3  5  3]
 [ 1  0 -2 -1]
 [-4 -4 -2  1]
 [-5  0  0  1]
 [ 1  3 -3 -1]
 [-3  3 -5 -4]]

Массив ar2:
[[ 0  1  0  3]
 [ 5  2  0  0]
 [-5  0 -3 -3]
 [ 2  5  5 -1]
 [-3 -3  4 -1]
 [-3  2  1 -3]
 [ 2  2  3  4]
 [-1  1  4  0]
 [-3  0  0 -3]
 [ 4  1 -1  3]]

Результат:
[[ 4  0  0  0]
 [ 0 10  6  0]
 [-8 10  0  6]
 [ 0  0  0  0]
 [ 2  0 10  6]
 [ 2  0  0 -2]
 [ 0  0  0  0]
 [ 0  0  0  2]
 [ 2  6  0 -2]
 [ 0  6  0  0]]


In [3]:
import numpy as np

# Создаем массив размерности (25, 4) со случайными целыми числами от 0 до 15
ar1 = np.random.randint(0, 16, size=(25, 4))

# Находим максимальные значения в каждой строке
max_in_rows = np.max(ar1, axis=1, keepdims=True)

# Создаем массив, где True - если элемент максимальный в своей строке
is_max = (ar1 == max_in_rows)

# Считаем количество максимальных элементов в каждом столбце
max_counts_per_col = np.sum(is_max, axis=0)

# Находим столбцы, где не менее 5 максимальных значений
cols_with_5max = np.where(max_counts_per_col >= 5)[0]
print(f"Столбцы, где не менее 5 раз встречается максимальное значение строки: {cols_with_5max}")

# Находим столбец с наибольшим количеством максимумов
col_with_most_max = np.argmax(max_counts_per_col)

# Заменяем максимумы по строке на -1 в этом столбце
ar1[(is_max[:, col_with_most_max]), col_with_most_max] = -1

print("\nМассив после замены:")
print(ar1)

Столбцы, где не менее 5 раз встречается максимальное значение строки: [0 1 3]

Массив после замены:
[[ 5 -1  8  7]
 [12 -1 10  5]
 [ 7 -1  5  7]
 [13 -1  0  3]
 [ 3 -1  1 11]
 [ 7 -1  2  9]
 [ 7  8  2 13]
 [ 1  3  3  6]
 [ 2 -1 11 14]
 [ 0  5  5  6]
 [14 -1  3  9]
 [ 0  5  3  9]
 [ 8  8 10  7]
 [ 2  2  3  0]
 [12  5 13  0]
 [ 7 -1  6  1]
 [12  5  3  2]
 [ 6  7  9 11]
 [ 4  1  0  2]
 [12 11  4  0]
 [15  8 14  5]
 [ 4 -1  2  0]
 [ 8  6  5 14]
 [10  1  9 10]
 [ 5  3  1 10]]


In [ ]:
import numpy as np

# Создаем массив 30x4 со случайными целыми числами от 0 до 100
vectors = np.random.randint(0, 101, size=(30, 4))

# Вычисляем евклидову норму (длину) каждого вектора
norms = np.linalg.norm(vectors, axis=1)

# Находим индексы 5 векторов с наибольшей длиной
top5_indices = np.argsort(norms)[-5:]

# Получаем сами векторы с наибольшей длиной
top5_vectors = vectors[top5_indices]

print("Исходный массив векторов:")
print(vectors)
print("\n5 векторов с наибольшей длиной:")
print(top5_vectors)

In [ ]:
import numpy as np

def one_hot_encoding(arr):
    # Определяем количество уникальных классов (начинаем с 0)
    num_classes = np.max(arr) + 1

    # Создаем матрицу one-hot encoding
    encoding = np.zeros((len(arr), num_classes), dtype=int)

    # Заполняем единицами соответствующие позиции
    encoding[np.arange(len(arr)), arr] = 1

    return encoding

# Тестирование на случайном массиве
random_array = np.random.randint(0, 5, size=10)  # Числа от 0 до 4, длина 10
print("Исходный массив:")
print(random_array)
print("\nOne-hot encoding:")
print(one_hot_encoding(random_array))

# Тест на примере из задания
test_array = np.array([2, 3, 2, 2, 2, 1])
print("\nТестовый массив:")
print(test_array)
print("\nOne-hot encoding для тестового массива:")
print(one_hot_encoding(test_array))

In [ ]:
import numpy as np

# Создаем массив 10x4 со случайными целыми числами от 0 до 50
arr = np.random.randint(0, 51, size=(10, 4))

# Находим уникальные элементы и их частоты
unique, counts = np.unique(arr, return_counts=True)

# Находим максимальную частоту
max_count = np.max(counts)

# Находим все числа с максимальной частотой
most_frequent_numbers = unique[counts == max_count]

print("Исходный массив:")
print(arr)
print("\nСамое частое число(а):", most_frequent_numbers)
print("Количество вхождений:", max_count)

# Создаем маску для всех позиций, где встречаются самые частые числа
mask = np.isin(arr, most_frequent_numbers)

# Считаем количество самых частых чисел в каждой строке
counts_per_row = np.sum(mask, axis=1)

# Находим индексы 3 строк с наибольшим количеством частых чисел
top3_rows = np.argsort(counts_per_row)[-3:]

# Получаем итоговый массив 3x4
result = arr[top3_rows]

print("\nСтроки с наибольшим количеством самых частых чисел:")
print(result)